# Background and foreground colors
background = #00212e
foreground = #eaeee9

# Standard colors
palette = 0=#00212e
palette = 1=#f5687a
palette = 2=#50e2bc
palette = 3=#c3feff
palette = 4=#6fbcd8
palette = 5=#97add0
palette = 6=#24c4e2
palette = 7=#eaeee9

# Bright colors
palette = 8=#5d6267
palette = 9=#ff6676
palette = 10=#7eddc4
palette = 11=#b6ffff
palette = 12=#00b8fa
palette = 13=#a8c4f0
palette = 14=#00bad1
palette = 15=#eaeee9
