$color = rgba(0, 33, 46, 1)
$inner_color = rgba(0, 33, 46, 0.66)
$outer_color = rgba(151, 173, 208, 1)
$font_color = rgba(234, 238, 233, 1)
$placeholder_color = rgba(234, 238, 233, 0.7)
$check_color = rgba(36, 196, 226, 1)
