background            #00212e
foreground            #eaeee9

# black
color0  #00212e
color8  #5d6267

# red
color1  #f5687a
color9  #ff6676

# green
color2  #50e2bc
color10 #7eddc4

# yellow
color3  #c3feff
color11 #b6ffff

# blue
color4  #6fbcd8
color12 #00b8fa

# magenta
color5  #97add0
color13 #a8c4f0

#cyan
color6  #24c4e2
color14 #00bad1

#white
color7  #eaeee9
color15 #eaeee9


